version: '3.8'

services:
  # Volume initialization service to ensure proper permissions
  init-volume:
    image: alpine:latest
    container_name: muse-volume-init
    command: sh -c "mkdir -p /db_files /logs && chmod -R 777 /db_files /logs && echo 'Volumes initialized with proper permissions'"
    volumes:
      - ./db_files:/db_files
      - ./logs:/logs  # Add this line
    restart: "no"
    mem_limit: 64M

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENVIRONMENT=${ENVIRONMENT:-production}
    container_name: muse-observatory-app
    restart: unless-stopped
    depends_on:
      - init-volume
    ports:
      - "${APP_PORT:-8080}:8080"
    volumes:
      # Mount source code in development
      - ${PWD}:/app${MOUNT_SUFFIX:-}
      # Mount local db_files directory directly
      - ./db_files:/app/db_files:rw
      - ./logs:/app/logs:rw
    environment:
      # Application configuration
      - HOST=0.0.0.0
      - PORT=8080
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - DEBUG=${DEBUG:-false}
      - DB_DIR=/app/db_files

      # Python configuration
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONPATH=/app

      # Logging
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    networks:
      - muse-network
    # Moderate resource limits for 4GB systems
    deploy:
      resources:
        limits:
          memory: 1.5G
        reservations:
          memory: 512M
    # Health check with longer intervals to reduce overhead
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/health || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: python app.py

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    container_name: muse-fact-scheduler
    restart: unless-stopped
    depends_on:
      - app
    volumes:
      - ./db_files:/app/db_files:rw
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/app/logs:rw
    environment:
      - DB_DIR=/app/db_files
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONPATH=/app
    entrypoint: ["/app/start-cron.sh"]
    restart: "no"
    networks:
      - muse-network

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/ssl/certs/cloudflare.crt:/etc/ssl/certs/cloudflare.crt:ro
      - /etc/ssl/private/cloudflare.key:/etc/ssl/private/cloudflare.key:ro
    depends_on:
      - app
    networks:
      - muse-network

networks:
  muse-network:
    driver: bridge
    name: muse_observatory_network
