version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: muse-observatory-db
    restart: always
    environment:
      POSTGRES_USER: museuser
      POSTGRES_PASSWORD: musepassword
      POSTGRES_DB: muse_observatory
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U museuser -d muse_observatory"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - muse-network

  app:
    build: .
    container_name: muse-observatory-app
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=muse_observatory
      - DB_USER=museuser
      - DB_PASSWORD=musepassword
    networks:
      - muse-network

networks:
  muse-network:
    driver: bridge

volumes:
  postgres-data: